'use strict';
const KEY='tang-soul-mirror-v1';
let DATA,state={history:[],unlocked:[],scenes:{},draft:[]},answers=[],step=0,busy=false,audioCtx,audioGain,audioNodes=[];
const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const getPoet=id=>DATA.poets.find(p=>p.id===id);
function loadState(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.history)&&Array.isArray(s.unlocked)&&s.scenes)state={...state,...s};}catch(e){/* Private storage may be unavailable. */}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){toast('瀏覽器未允許儲存，這次體驗仍可繼續。');}}
function unlock(id){if(!state.unlocked.includes(id))state.unlocked.push(id);save();}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2500);}
function go(route){location.hash=route;}
function show(html){app.innerHTML=`<div class="fade">${html}</div>`;window.scrollTo(0,0);}
function tags(p){return `<div class="tags">${p.tag.replace(/。$/,'').split('、').map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`;}
function seal(p){return `<span class="seal">${esc(p.stamp.slice(0,2))}<br>${esc(p.stamp.slice(2))}</span>`;}
function poemBlock(p){return `<article class="poem-block"><h3>《${esc(p.title)}》</h3><div class="quote">${esc(p.quote)}</div><p class="label">詩句解碼</p><p>${esc(p.insight)}</p><div class="prescription"><span class="label">現代處方</span><p>${esc(p.prescription)}</p></div><a href="${esc(p.source)}" target="_blank" rel="noopener noreferrer">核對原詩 ↗</a></article>`;}
const landscape=`<svg class="mountains" viewBox="0 0 500 460" preserveAspectRatio="xMidYMax slice" aria-hidden="true"><defs><linearGradient id="mist" x2="0" y2="1"><stop stop-color="#4B5563" stop-opacity=".2"/><stop offset="1" stop-color="#F6F3EE" stop-opacity=".1"/></linearGradient><filter id="blur"><feGaussianBlur stdDeviation="1.5"/></filter></defs><path d="M0 290L65 242L109 260L162 175L198 222L251 150L318 247L372 222L422 276L500 218V460H0Z" fill="url(#mist)" filter="url(#blur)"/><path d="M0 363L75 321L130 349L210 285L255 320L310 283L375 360L442 329L500 352V460H0Z" fill="#4B5563" opacity=".13"/><path d="M0 437Q125 368 270 420T500 399V460H0Z" fill="#2B2B2B" opacity=".16"/><path d="M160 412q60-18 120 0" fill="none" stroke="#4B5563" opacity=".45" stroke-width="2"/><path d="M231 402v-33l17 22h-17" stroke="#2B2B2B" fill="none" stroke-width="1.5"/><path d="M210 406q28 17 52 0" fill="#2B2B2B" opacity=".6"/></svg>`;
function home(){show(`<section class="hero"><div class="hero-copy"><p class="eyebrow">SOUL MIRROR · VOICES OF TANG POETS</p><h1>唐詩心印<br>長安靈魂迴響</h1><p>千年前，他們也曾疲憊、失落、身不由己。<br>六段日常抉擇，找到與你共振的生命回聲。</p><p class="muted">品讀唐詩，找到屬於自己的心靈印像。</p><div class="actions"><button class="btn primary" data-action="start">開始心靈鏡鑑 →</button><a class="btn" href="#library">先逛詩魂藏閣</a></div><p class="muted" style="margin-top:18px;font-size:12px">約 3-5 分鐘 · 無須登入 · 沒有標準答案</p></div><div class="hero-art"><div class="moon"></div>${landscape}<div class="vertical">在詩裡，看見自己。</div><div class="art-seal">長安<br>迴響</div></div></section><div class="journey"><div><strong><span>01</span>情境投射</strong>從日常選擇照見內心</div><div><strong><span>02</span>靈魂共振</strong>八種精神，沒有高下</div><div><strong><span>03</span>時空對弈</strong>走進四段文學微劇場</div><div><strong><span>04</span>文化處方籤</strong>帶走一張屬於你的心印</div></div>${state.history.length?`<section class="history"><p class="label">最近的心印</p>${state.history.slice(0,3).map((r,i)=>`<button class="small-btn" data-action="history" data-index="${i}">${esc(getPoet(r.poet)?.name||'')} · ${new Date(r.time).toLocaleDateString('zh-TW')}</button>`).join('')}${state.draft.length?`<button class="small-btn" data-action="resume">繼續未完成的鏡鑑</button>`:''}</section>`:state.draft.length?'<div class="history"><button class="small-btn" data-action="resume">繼續未完成的鏡鑑</button></div>':''}<details><summary>關於這次探索</summary><p>以企劃中的八位文人心靈印像為起點。原四題保留，增補兩題，讓每位文人都出現三次。結果是文學性的自我探索，不是經科學驗證的人格量表，也不是心理診斷。</p><p>七位唐代文人，加上北宋蘇東坡的精神延展。選詩不全屬於《唐詩三百首》；生平敘述保留企劃原意，有疑義處另附考據提醒。</p></details>`);}
function start(resume=false){answers=resume?state.draft.slice():[];step=answers.length;if(step>=DATA.questions.length)step=0;busy=false;state.draft=answers.slice();save();if(location.hash==='#quiz')quiz();else go('quiz');}
function quiz(){const q=DATA.questions[step];show(`<section class="quiz-wrap"><div class="section-head"><span class="eyebrow">心靈鏡鑑 · ${String(step+1).padStart(2,'0')} / 06</span><span class="muted">選最接近你的，不選「應該」的。</span></div><div class="progress" aria-label="第 ${step+1} 題，共 6 題">${DATA.questions.map((_,i)=>`<i class="${i<=step?'done':''}"></i>`).join('')}</div><p class="question-context">${esc(q.context)}</p><h2>${esc(q.prompt)}</h2>${q.options.map((o,i)=>`<button class="option" data-action="answer" data-index="${i}"><span>${String.fromCharCode(65+i)}</span>${esc(o.text)}</button>`).join('')}<div class="section-head" style="margin-top:18px">${step?'<button class="small-btn" data-action="back">← 上一題</button>':'<a class="small-btn" href="#home">← 回到卷首</a>'}<span class="muted" style="font-size:12px">進度會留在這台裝置</span></div></section>`);}
function calculate(a){const scores=DATA.poets.map(()=>0);a.forEach((answer,i)=>{const o=DATA.questions[i]?.options[answer];const idx=DATA.poets.findIndex(p=>p.id===o?.poet);if(idx>=0)scores[idx]++;});const max=Math.max(...scores);const tied=DATA.poets.filter((p,i)=>scores[i]===max);let poet=tied[0];for(let i=a.length-1;i>=0;i--){const id=DATA.questions[i].options[a[i]].poet;const match=tied.find(p=>p.id===id);if(match){poet=match;break;}}return {poet:poet.id,scores,tied:tied.map(p=>p.id)};}
function finish(){const result={...calculate(answers),answers:answers.slice(),time:new Date().toISOString()};state.history.unshift(result);state.history=state.history.slice(0,20);state.draft=[];unlock(result.poet);save();go('result');if(navigator.vibrate&&!matchMedia('(prefers-reduced-motion: reduce)').matches)navigator.vibrate(30);}
function radar(scores){const cx=160,cy=160,r=102;const point=(i,v)=>`${cx+Math.cos(-Math.PI/2+i*Math.PI/4)*r*v},${cy+Math.sin(-Math.PI/2+i*Math.PI/4)*r*v}`;return `<svg class="radar" viewBox="0 0 320 320" role="img" aria-label="八維偏好圖，數值代表所選選項的次數，不是人格能力分數">${[.33,.66,1].map(v=>`<polygon points="${DATA.poets.map((_,i)=>point(i,v)).join(' ')}" fill="none" stroke="#d9d4ca"/>`).join('')}${DATA.poets.map((_,i)=>`<line x1="160" y1="160" x2="${point(i,1).split(',')[0]}" y2="${point(i,1).split(',')[1]}" stroke="#d9d4ca"/>`).join('')}<polygon points="${scores.map((s,i)=>point(i,s/3)).join(' ')}" fill="#B91C1C22" stroke="#B91C1C" stroke-width="1.5"/>${DATA.dimensions.map((d,i)=>{const p=point(i,1.31).split(',');return `<text x="${p[0]}" y="${+p[1]+4}" text-anchor="middle" fill="#4B5563" font-size="11">${d.slice(0,-1)}</text>`;}).join('')}</svg>`;}
function result(index=0){const r=state.history[index];if(!r){show('<div class="empty"><h2>你的詩卷還未展開</h2><button class="btn primary" data-action="start">開始鏡鑑</button></div>');return;}const p=getPoet(r.poet);const poem=p.poems[0];show(`<p class="eyebrow">靈魂共振 · 你的本命詩人</p><div class="result-grid"><section><div class="result-title"><h1 class="poet-name">${esc(p.name)}</h1>${seal(p)}</div><h3>${esc(p.archetype)}</h3>${tags(p)}<p>${esc(p.essence)}</p><div class="quote">${esc(poem.quote.replace(/，/g,'，\n'))}</div><p class="muted">${esc(p.name)}《${esc(poem.title)}》</p><div class="prescription"><span class="label">今天的心靈處方</span><p>${esc(poem.prescription)}</p></div><div class="actions"><a class="btn primary" href="#${DATA.scenes.some(s=>s.id===p.id)?'scene/'+p.id:'theatre'}">走進時空對弈 →</a><a class="btn" href="#poet/${p.id}">讀懂${esc(p.name)}</a></div></section><section><div class="panel"><p class="label">你的八維共振</p>${radar(r.scores)}<div class="meter-list">${r.scores.map((n,i)=>`<div><div class="meter-label"><span>${DATA.dimensions[i]}</span><span>${n} / 3</span></div><div class="meter"><b style="width:${n/3*100}%"></b></div></div>`).join('')}</div><p class="muted" style="font-size:11px;margin:18px 0 0">每位詩人出現三次。數值是偏好線索，不是能力分數。${r.tied.length>1?`同時共振：${r.tied.map(id=>getPoet(id).name).join('、')}；以最後一次相關選擇定本命。`:''}</p></div><div class="actions"><button class="btn red" data-action="card" data-poet="${p.id}">生成我的文化籤</button><button class="small-btn" data-action="start">再照一次鏡鑑</button></div></section></div>`);}
function library(){show(`<div class="section-head"><div><p class="eyebrow">詩魂藏閣 · ${state.unlocked.length} / 8 心印已收藏</p><h2>八種人生，八種安放心的方法。</h2></div><input class="search" id="search" aria-label="搜尋詩人、標籤或詩名" placeholder="搜尋詩人、標籤或詩名"></div><p class="muted">圖鑑全部可閱讀。完成鏡鑑或微劇場，會留下你的收藏印記。</p><div class="library-grid" id="poet-grid">${tiles(DATA.poets)}</div><details><summary>閱讀與考據說明</summary><p>人生軌跡保存企劃原文；它含有現代比喻與尚待核實的軼事，不是學術傳記。每位詩人頁面附考據提醒，每首節引附原詩來源。詩句解碼與現代處方是本遊戲的文學轉譯。</p><p>蘇東坡為北宋文人。圖鑑中的 18 首作品，不全出自《唐詩三百首》。</p></details>`);document.querySelector('#search').addEventListener('input',e=>{const term=e.target.value.trim();const found=DATA.poets.filter(p=>[p.name,p.tag,...p.poems.map(x=>x.title)].join(' ').includes(term));document.querySelector('#poet-grid').innerHTML=found.length?tiles(found):'<p class="empty">沒有找到相符的詩卷。</p>';});}
function tiles(ps){return ps.map(p=>`<button class="poet-tile" data-action="poet" data-poet="${p.id}"><span class="tile-no">${String(DATA.poets.indexOf(p)+1).padStart(2,'0')} ${p.id==='su'?'· 宋代延展':''}</span><h3>${esc(p.name)}</h3><p class="muted" style="margin:0">${esc(p.archetype)}</p><span class="badge">${state.unlocked.includes(p.id)?'印記已收藏':'開卷閱讀 →'}</span></button>`).join('');}
function profile(id){const p=getPoet(id);if(!p){home();return;}show(`<a class="small-btn" href="#library">← 詩魂藏閣</a><div class="profile-top"><section><p class="eyebrow" style="margin-top:25px">${p.id==='su'?'北宋 · 精神延展':'唐代 · 詩人心印'}</p><div class="result-title"><h1 class="poet-name">${esc(p.name)}</h1>${seal(p)}</div><h3>${esc(p.archetype)}</h3>${tags(p)}<p>${esc(p.essence)}</p><button class="btn red" data-action="card" data-poet="${p.id}">帶走這張文化籤</button></section><section><p class="label">人生軌跡 · 企劃敘述</p><p>${esc(p.trajectory)}</p>${p.notes.length?`<aside class="notes"><p class="label">考據提醒</p>${p.notes.map(n=>`<p>${esc(n)}</p>`).join('')}</aside>`:''}<div class="prescription"><span class="label">心靈解法</span><p>${esc(p.prescription)}</p></div></section></div><div class="poem-list">${p.poems.map(poemBlock).join('')}</div><details><summary>精神雷達 · 文學角色設定</summary><p>這些數值是遊戲的角色設定，不是歷史人物的心理測量結果。</p>${Object.entries(p.spiritual_radar).map(([k,v])=>`<div class="meter-label"><span>${({resilience:'韌性',detachment:'超然',authenticity:'本真',optimism:'樂觀'})[k]}</span><span>${v}</span></div><div class="meter"><b style="width:${v}%"></b></div>`).join('')}</details>`);}
function theatre(){show(`<p class="eyebrow">時空對弈 · ${Object.keys(state.scenes).length} / 4 卷已完成</p><h2>如果那一刻，換你站在詩人身旁。</h2><p class="muted">四段文學改編微劇場。沒有答對或答錯，也不宣稱重演史實。<br>每一條路，都有一種看見自己的方式。</p><div class="theatre-grid">${DATA.scenes.map((s,i)=>`<button class="scene-tile" data-action="scene" data-poet="${s.id}"><span class="scene-symbol">${['燈','舟','信','海'][i]}</span><p class="eyebrow">${esc(s.subtitle)}</p><h3>${esc(s.name)}</h3><p class="muted">${esc(s.text.slice(0,37))}…</p><span class="badge">${state.scenes[s.id]?'已完成 · 再走另一條路':'展開這一卷 →'}</span></button>`).join('')}</div>`);}
function scene(id,choice){const s=DATA.scenes.find(s=>s.id===id);if(!s){theatre();return;}const p=getPoet(id);show(`<section class="scene-content"><a class="small-btn" href="#theatre">← 四卷時空對弈</a><p class="eyebrow" style="margin-top:25px">${esc(s.subtitle)}</p><h2>${esc(s.name)}</h2><p class="scene-text">${esc(s.text)}</p>${choice===undefined?s.choices.map((c,i)=>`<button class="option" data-action="choice" data-poet="${id}" data-index="${i}"><span>${i?'乙':'甲'}</span>${esc(c.text)}</button>`).join(''):`<div class="outcome"><span class="label">你的這一步 · ${esc(s.choices[choice].text)}</span><p style="margin:15px 0 0">${esc(s.choices[choice].outcome)}</p></div><p class="label">詩卷已解鎖</p><div class="poem-list">${p.poems.filter(x=>s.poems.includes(x.title)).map(poemBlock).join('')}</div><div class="actions"><button class="btn red" data-action="card" data-poet="${id}">生成這一卷的文化籤</button><button class="btn" data-action="scene" data-poet="${id}">試試另一個選擇</button><a class="btn" href="#theatre">再訪其他詩人</a></div>`}<p class="muted" style="font-size:12px;margin-top:22px">文學改編，情境與對白為遊戲創作。${id==='liu'?'託孤養育細節待核實。':id==='su'?'食蠔軼事與詩作並非同一時間的史實場景。':''}</p></section>`);}
function wrap(ctx,text,x,y,width,lineHeight){let line='';for(const char of text){if(char==='\n'){ctx.fillText(line,x,y);line='';y+=lineHeight;continue;}if(ctx.measureText(line+char).width>width&&line){ctx.fillText(line,x,y);line=char;y+=lineHeight;}else line+=char;}if(line)ctx.fillText(line,x,y);return y+lineHeight;}
async function drawCard(p,format='square'){await Promise.race([document.fonts.ready,new Promise(r=>setTimeout(r,4000))]);const canvas=document.querySelector('#share-canvas');if(!canvas)return;canvas.width=1080;canvas.height=format==='portrait'?1920:1080;const c=canvas.getContext('2d'),h=canvas.height,tall=h>1100;let seed=24;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};c.fillStyle='#F6F3EE';c.fillRect(0,0,1080,h);for(let i=0;i<8000;i++){c.fillStyle=`rgba(70,60,45,${rand()*.035})`;c.fillRect(rand()*1080,rand()*h,1+rand()*2,1+rand()*2);}const g=c.createRadialGradient(960,h*.75,0,960,h*.75,550);g.addColorStop(0,'#4B556325');g.addColorStop(1,'#4B556300');c.fillStyle=g;c.fillRect(0,0,1080,h);c.strokeStyle='#d9d4ca';c.lineWidth=2;c.strokeRect(48,48,984,h-96);c.fillStyle='#B91C1C';c.font='26px sans-serif';c.fillText('唐 詩 心 印  /  長 安 靈 魂 迴 響',90,110);c.fillStyle='#4B5563';c.font='26px sans-serif';c.fillText('與你共振的生命回聲',90,tall?230:190);c.fillStyle='#2B2B2B';c.font=`600 ${p.name.length===3?125:148}px "Noto Serif TC",serif`;c.fillText(p.name,82,tall?440:365);c.save();c.translate(872,tall?350:300);c.rotate(-.07);c.fillStyle='#B91C1C';c.fillRect(-57,-57,114,114);c.strokeStyle='#F6F3EE';c.lineWidth=3;c.strokeRect(-50,-50,100,100);c.fillStyle='#F6F3EE';c.font='38px "Noto Serif TC",serif';c.fillText(p.stamp.slice(0,2),-40,-6);c.fillText(p.stamp.slice(2),-40,38);c.restore();c.fillStyle='#B91C1C';c.font='32px "Noto Serif TC",serif';c.fillText(p.archetype,90,tall?530:435);c.fillStyle='#4B5563';c.font='30px sans-serif';wrap(c,p.essence,90,tall?625:500,850,48);c.strokeStyle='#d9d4ca';c.beginPath();c.moveTo(90,tall?830:650);c.lineTo(990,tall?830:650);c.stroke();const poem=p.poems[0];c.fillStyle='#2B2B2B';c.font=`600 ${tall?44:36}px "Noto Serif TC",serif`;let y=wrap(c,poem.quote.replace(/，/g,'，\n'),90,tall?960:690,850,tall?72:50);c.fillStyle='#4B5563';c.font='24px sans-serif';c.fillText(`《${poem.title}》`,90,y+12);if(!tall){c.fillStyle='#4B5563';c.font='22px sans-serif';wrap(c,poem.insight,90,y+57,850,33);}if(tall){c.fillStyle='#B91C1C';c.font='27px sans-serif';c.fillText('詩 句 解 碼',90,1220);c.fillStyle='#4B5563';c.font='32px "Noto Serif TC",serif';wrap(c,poem.insight,90,1290,850,55);c.fillStyle='#B91C1C';c.font='27px sans-serif';c.fillText('今 日 的 心 靈 處 方',90,1500);c.fillStyle='#2B2B2B';c.font='32px "Noto Serif TC",serif';wrap(c,poem.prescription,90,1570,850,55);}c.fillStyle='#B91C1C';c.font='26px "Noto Serif TC",serif';c.fillText('一人一印 · 邀你照見自己的詩魂',90,h-(tall?140:90));c.fillStyle='#4B5563';c.font='22px sans-serif';c.fillText('品讀唐詩，找到屬於自己的心靈印像。',90,h-(tall?90:55));canvas.dataset.poet=p.id;}
function card(id){const p=getPoet(id);if(!p){home();return;}show(`<div class="section-head"><div><p class="eyebrow">文化處方籤 · ${esc(p.name)}</p><h2>把此刻的心印，留在身邊。</h2></div><a class="small-btn" href="#result">← 回到我的鏡鑑</a></div><div class="format-row"><label for="format" class="muted">畫幅</label><select id="format"><option value="square">方形 1080 × 1080</option><option value="portrait">直式 1080 × 1920</option></select><button class="btn red" data-action="download">下載 PNG</button><button class="btn" data-action="share">分享心印</button><button class="small-btn" data-action="copy">複製遊戲連結</button></div><canvas id="share-canvas" class="card-preview" aria-label="${esc(p.name)}文化處方籤"></canvas><p class="muted" style="text-align:center;font-size:12px">分享按鈕使用裝置的分享選單，不會自動發布到社群。<br>若裝置不支援圖片分享，請先下載再自行傳送。圖卡不包含測驗作答紀錄。</p>`);drawCard(p);document.querySelector('#format').addEventListener('change',e=>drawCard(p,e.target.value));}
function blob(){return new Promise(resolve=>document.querySelector('#share-canvas').toBlob(resolve,'image/png'));}
function gameUrl(){return location.href.split('#')[0];}
async function share(){const b=await blob();if(!b){toast('圖卡尚未準備好，請稍後再試。');return;}const f=new File([b],'唐詩心印.png',{type:'image/png'});try{if(navigator.canShare?.({files:[f]})){await navigator.share({files:[f],title:'唐詩心印',text:'找到與你共振的生命回聲。',url:gameUrl()});}else if(navigator.share){await navigator.share({title:'唐詩心印',text:'找到與你共振的生命回聲。',url:gameUrl()});}else{download();toast('已下載圖卡，請自行傳送給朋友。');}}catch(e){if(e.name!=='AbortError')toast('分享未完成，仍可下載圖卡。');}}
function download(){const c=document.querySelector('#share-canvas');const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download=`唐詩心印-${getPoet(c.dataset.poet).name}-${c.width}x${c.height}.png`;a.click();toast('圖卡已準備下載。手機也可長按圖片儲存。');}
async function copy(){try{await navigator.clipboard.writeText(gameUrl());toast('已複製遊戲連結。');}catch(e){toast('無法使用剪貼簿，請複製瀏覽器網址。');}}
function route(){if(!DATA)return;const [page,id]=location.hash.slice(1).split('/');busy=false;switch(page){case 'quiz':quiz();break;case 'result':result(Number(id)||0);break;case 'library':library();break;case 'poet':profile(id);break;case 'theatre':theatre();break;case 'scene':scene(id);break;case 'card':card(id);break;default:home();}}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action,index,poet}=b.dataset;switch(action){case 'start':start();break;case 'resume':start(true);break;case 'answer':if(busy)return;busy=true;answers[step]=Number(index);state.draft=answers.slice(0,step+1);save();b.classList.add('chosen');const ripple=document.createElement('i');ripple.className='ripple';ripple.style.left='50%';ripple.style.top='50%';b.append(ripple);setTimeout(()=>{if(location.hash!=='#quiz'){busy=false;return;}if(step===DATA.questions.length-1)finish();else{step++;busy=false;quiz();}},300);break;case 'back':answers=answers.slice(0,--step);state.draft=answers.slice();save();quiz();break;case 'history':go('result/'+index);break;case 'poet':go('poet/'+poet);break;case 'scene':if(location.hash==='#scene/'+poet)scene(poet);else go('scene/'+poet);break;case 'choice':state.scenes[poet]={choice:Number(index),time:new Date().toISOString()};unlock(poet);scene(poet,Number(index));break;case 'card':go('card/'+poet);break;case 'download':download();break;case 'share':share();break;case 'copy':copy();break;}});
document.querySelector('#reset').addEventListener('click',()=>{if(confirm('清除這台裝置的測驗、收藏與劇場紀錄？此動作無法復原。')){state={history:[],unlocked:[],scenes:{},draft:[]};answers=[];step=0;save();route();toast('本機紀錄已清除。');}});
document.querySelector('#audio').addEventListener('click',async()=>{const b=document.querySelector('#audio');try{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();audioGain=audioCtx.createGain();audioGain.gain.value=0;audioGain.connect(audioCtx.destination);[130.81,196,261.63].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.value=.07/(i+1);o.connect(g);g.connect(audioGain);o.start();audioNodes.push(o);});}await audioCtx.resume();const on=b.getAttribute('aria-pressed')!=='true';audioGain.gain.setTargetAtTime(on?.45:0,audioCtx.currentTime,.5);b.setAttribute('aria-pressed',String(on));b.textContent=on?'音境 開':'音境 關';toast(on?'合成環境音已開啟，非古琴錄音。':'音境已關閉。');}catch(e){toast('此瀏覽器暫不支援音境。');}});
window.addEventListener('hashchange',route);
fetch('data.json').then(r=>{if(!r.ok)throw Error('data');return r.json();}).then(d=>{DATA=d;loadState();answers=state.draft.slice();step=Math.min(answers.length,DATA.questions.length-1);route();}).catch(()=>{show('<div class="empty"><h2>詩卷暫時未能展開</h2><p>請確認網路連線後重新整理。</p><button class="btn" onclick="location.reload()">重新整理</button></div>');});
